/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author cauas
 */
public class MenuInicial extends javax.swing.JFrame {
    CadastroColaboradores CadastroC = new CadastroColaboradores();
    CadastroAlocacao aloc = new CadastroAlocacao();
    CadastroEmpresa CadastroE = new CadastroEmpresa();

    /**
     * Creates new form Interface
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnColaboradores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAlocacao = new javax.swing.JButton();
        btnEmpresas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu inicial");
        setResizable(false);

        jPanel1.setLayout(null);

        btnColaboradores.setBackground(new java.awt.Color(204, 204, 204));
        btnColaboradores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnColaboradores.setForeground(new java.awt.Color(0, 0, 0));
        btnColaboradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/adicionar-usuario (1).png"))); // NOI18N
        btnColaboradores.setText("Cadastro de colaboradores");
        btnColaboradores.setPreferredSize(new java.awt.Dimension(185, 30));
        btnColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaboradoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnColaboradores);
        btnColaboradores.setBounds(580, 420, 230, 50);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("MENU INICIAL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 280, 350, 80);

        btnAlocacao.setBackground(new java.awt.Color(204, 204, 204));
        btnAlocacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlocacao.setForeground(new java.awt.Color(0, 0, 0));
        btnAlocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/adicionar-usuario (1).png"))); // NOI18N
        btnAlocacao.setText("Alocação de prestadores");
        btnAlocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlocacaoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlocacao);
        btnAlocacao.setBounds(30, 420, 220, 50);

        btnEmpresas.setBackground(new java.awt.Color(204, 204, 204));
        btnEmpresas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEmpresas.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/adicionar-usuario (1).png"))); // NOI18N
        btnEmpresas.setText("Cadastro de Empresas");
        btnEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresasActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpresas);
        btnEmpresas.setBounds(300, 420, 230, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/login.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaboradoresActionPerformed
        CadastroC.setVisible(true);
    }//GEN-LAST:event_btnColaboradoresActionPerformed

    private void btnAlocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlocacaoActionPerformed
        aloc.setVisible(true);
    }//GEN-LAST:event_btnAlocacaoActionPerformed

    private void btnEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresasActionPerformed
        CadastroE.setVisible(true);
    }//GEN-LAST:event_btnEmpresasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlocacao;
    private javax.swing.JButton btnColaboradores;
    private javax.swing.JButton btnEmpresas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
